In [2]:
import pandas as pd

In [3]:
data = pd.read_csv('diabetes.csv')

In [4]:
data.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [5]:
predictors_df = data.loc[:,data.columns!='Outcome']
target_df = data['Outcome']

In [6]:
predictors_df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
0,6,148,72,35,0,33.6,0.627,50
1,1,85,66,29,0,26.6,0.351,31
2,8,183,64,0,0,23.3,0.672,32
3,1,89,66,23,94,28.1,0.167,21
4,0,137,40,35,168,43.1,2.288,33

In [7]:
timestamps = pd.date_range(end = pd.Timestamp.now(),
                           periods = len(data),freq = 'D').to_frame(name = 'event_timestamp', index = False)

In [8]:
timestamps

               event_timestamp
0   2022-11-11 14:52:13.664794
1   2022-11-12 14:52:13.664794
2   2022-11-13 14:52:13.664794
3   2022-11-14 14:52:13.664794
4   2022-11-15 14:52:13.664794
..                         ...
763 2024-12-13 14:52:13.664794
764 2024-12-14 14:52:13.664794
765 2024-12-15 14:52:13.664794
766 2024-12-16 14:52:13.664794
767 2024-12-17 14:52:13.664794

[768 rows x 1 columns]

In [9]:
predictors_df = pd.concat(objs = [predictors_df, timestamps], axis = 1)
target_df = pd.concat(objs = [target_df, timestamps], axis =1)

In [10]:
predictors_df

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,event_timestamp
0,6,148,72,35,0,33.6,0.627,50,2022-11-11 14:52:13.664794
1,1,85,66,29,0,26.6,0.351,31,2022-11-12 14:52:13.664794
2,8,183,64,0,0,23.3,0.672,32,2022-11-13 14:52:13.664794
3,1,89,66,23,94,28.1,0.167,21,2022-11-14 14:52:13.664794
4,0,137,40,35,168,43.1,2.288,33,2022-11-15 14:52:13.664794
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,2024-12-13 14:52:13.664794
764,2,122,70,27,0,36.8,0.340,27,2024-12-14 14:52:13.664794
765,5,121,72,23,112,26.2,0.245,30,2024-12-15 14:52:13.664794
766,1,126,60,0,0,30.1,0.349,47,2024-12-16 14:52:13.664794
767,1,93,70,31,0,30.4,0.315,23,2024-12-17 14:52:13.664794

In [11]:


target_df.head()

   Outcome            event_timestamp
0        1 2022-11-11 14:52:13.664794
1        0 2022-11-12 14:52:13.664794
2        1 2022-11-13 14:52:13.664794
3        0 2022-11-14 14:52:13.664794
4        1 2022-11-15 14:52:13.664794

In [12]:
predictors_df['patient_id'] = list(range(len(data)))
target_df['patient_id'] = list(range(len(data)))

In [13]:
predictors_df

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,event_timestamp,patient_id
0,6,148,72,35,0,33.6,0.627,50,2022-11-11 14:52:13.664794,0
1,1,85,66,29,0,26.6,0.351,31,2022-11-12 14:52:13.664794,1
2,8,183,64,0,0,23.3,0.672,32,2022-11-13 14:52:13.664794,2
3,1,89,66,23,94,28.1,0.167,21,2022-11-14 14:52:13.664794,3
4,0,137,40,35,168,43.1,2.288,33,2022-11-15 14:52:13.664794,4
...,...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,2024-12-13 14:52:13.664794,763
764,2,122,70,27,0,36.8,0.340,27,2024-12-14 14:52:13.664794,764
765,5,121,72,23,112,26.2,0.245,30,2024-12-15 14:52:13.664794,765
766,1,126,60,0,0,30.1,0.349,47,2024-12-16 14:52:13.664794,766
767,1,93,70,31,0,30.4,0.315,23,2024-12-17 14:52:13.664794,767

In [14]:


target_df

     Outcome            event_timestamp  patient_id
0          1 2022-11-11 14:52:13.664794           0
1          0 2022-11-12 14:52:13.664794           1
2          1 2022-11-13 14:52:13.664794           2
3          0 2022-11-14 14:52:13.664794           3
4          1 2022-11-15 14:52:13.664794           4
..       ...                        ...         ...
763        0 2024-12-13 14:52:13.664794         763
764        0 2024-12-14 14:52:13.664794         764
765        0 2024-12-15 14:52:13.664794         765
766        1 2024-12-16 14:52:13.664794         766
767        0 2024-12-17 14:52:13.664794         767

[768 rows x 3 columns]

In [15]:
predictors_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 10 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Pregnancies               768 non-null    int64
 1   Glucose                   768 non-null    int64
 2   BloodPressure             768 non-null    int64
 3   SkinThickness             768 non-null    int64
 4   Insulin                   768 non-null    int64
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64
 8   event_timestamp           768 non-null    datetime64[ns]
 9   patient_id                768 non-null    int64
dtypes: datetime64[ns](1), float64(2), int64(7)
memory usage: 60.1 KB

In [30]:
predictors_df.to_parquet(path='/Users/bqkumar/Documents/Developements/feast_demo/my_project/feature_repo/data/predictors_df.parquet')
target_df.to_parquet(path='/Users/bqkumar/Documents/Developements/feast_demo/my_project/feature_repo/data/target_df.parquet')

In [31]:
!feast version

Feast SDK Version: "0.42.0"

In [21]:
!pwd

/Users/bqkumar/Documents/Developements/feast_demo

In [22]:
!ls

FeastGuideline.ipynb my_project           venv
diabetes.csv         test.py

In [23]:
cd my_project

/Users/bqkumar/Documents/Developements/feast_demo/my_project

/Users/bqkumar/Documents/Developements/feast_demo/venv/lib/python3.13/site-packages/IPython/core/magics/osm.py:417: UserWarning: This is now an optional IPython functionality, setting dhist requires you to install the `pickleshare` library.
  self.shell.db['dhist'] = compress_dhist(dhist)[-100:]

In [24]:
!ls

README.md    __init__.py  feature_repo

In [25]:
cd feature_repo

/Users/bqkumar/Documents/Developements/feast_demo/my_project/feature_repo

/Users/bqkumar/Documents/Developements/feast_demo/venv/lib/python3.13/site-packages/IPython/core/magics/osm.py:417: UserWarning: This is now an optional IPython functionality, setting dhist requires you to install the `pickleshare` library.
  self.shell.db['dhist'] = compress_dhist(dhist)[-100:]

In [37]:
!pwd

/Users/bqkumar/Documents/Developements/feast_demo/my_project/feature_repo

In [38]:
!feast apply

No project found in the repository. Using project name feature_repo defined in feature_store.yaml
Applying changes for project feature_repo
12/17/2024 03:27:58 PM root WARNING: Cannot use sqlite_vec for vector search
12/17/2024 03:27:58 PM root WARNING: Cannot use sqlite_vec for vector search
12/17/2024 03:27:58 PM root WARNING: Cannot use sqlite_vec for vector search
12/17/2024 03:27:58 PM root WARNING: Cannot use sqlite_vec for vector search
12/17/2024 03:27:58 PM root WARNING: Cannot use sqlite_vec for vector search
12/17/2024 03:27:58 PM root WARNING: Cannot use sqlite_vec for vector search
Created project feature_repo
Created entity patient_id
Created feature view target_df_feature_view
Created feature view predictors_df_feature_view

12/17/2024 03:27:58 PM root WARNING: Cannot use sqlite_vec for vector search
12/17/2024 03:27:58 PM root WARNING: Cannot use sqlite_vec for vector search
12/17/2024 03:27:58 PM root WARNING: Cannot use sqlite_vec for vector search
12/17/2024 03:27:58 PM root WARNING: Cannot use sqlite_vec for vector search
Created sqlite table feature_repo_predictors_df_feature_view
Created sqlite table feature_repo_target_df_feature_view
Deleted sqlite table my_project_driver_hourly_stats_fresh
Deleted sqlite table my_project_driver_hourly_stats

In [39]:
entity_df = pd.read_parquet(path='/Users/bqkumar/Documents/Developements/feast_demo/my_project/feature_repo/data/target_df.parquet')

In [40]:
entity_df

     Outcome            event_timestamp  patient_id
0          1 2022-11-11 14:52:13.664794           0
1          0 2022-11-12 14:52:13.664794           1
2          1 2022-11-13 14:52:13.664794           2
3          0 2022-11-14 14:52:13.664794           3
4          1 2022-11-15 14:52:13.664794           4
..       ...                        ...         ...
763        0 2024-12-13 14:52:13.664794         763
764        0 2024-12-14 14:52:13.664794         764
765        0 2024-12-15 14:52:13.664794         765
766        1 2024-12-16 14:52:13.664794         766
767        0 2024-12-17 14:52:13.664794         767

[768 rows x 3 columns]

In [41]:
from feast import FeatureStore
from feast.infra.offline_stores.file_source import SavedDatasetFileStorage

store = FeatureStore(repo_path='.')



training_data = store.get_historical_features(
    entity_df=entity_df,
    features=[
        "predictors_df_feature_view:Pregnancies",
        "predictors_df_feature_view:Glucose",
        "predictors_df_feature_view:BloodPressure",
        "predictors_df_feature_view:SkinThickness",
        "predictors_df_feature_view:Insulin",
        "predictors_df_feature_view:BMI",
        "predictors_df_feature_view:DiabetesPedigreeFunction",
        "predictors_df_feature_view:Age",
    ]
)

dataset = store.create_saved_dataset(
    from_=training_data,
    name="diabetes_dataset",
    storage=SavedDatasetFileStorage('data/diabetes_dataset.parquet')
)

/Users/bqkumar/Documents/Developements/feast_demo/venv/lib/python3.13/site-packages/feast/feature_store.py:1201: RuntimeWarning: Saving dataset is an experimental feature. This API is unstable and it could and most probably will be changed in the future. We do not guarantee that future changes will maintain backward compatibility.
  warnings.warn(

In [43]:
training_data.to_df()

,Outcome,event_timestamp,patient_id,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
0,1,2022-11-11 14:52:13.664794+00:00,0,6,148,72,35,0,33.6,0.627,50
1,0,2022-11-12 14:52:13.664794+00:00,1,1,85,66,29,0,26.6,0.351,31
2,1,2022-11-13 14:52:13.664794+00:00,2,8,183,64,0,0,23.3,0.672,32
3,0,2022-11-14 14:52:13.664794+00:00,3,1,89,66,23,94,28.1,0.167,21
4,1,2022-11-15 14:52:13.664794+00:00,4,0,137,40,35,168,43.1,2.288,33
...,...,...,...,...,...,...,...,...,...,...,...
763,0,2024-12-13 14:52:13.664794+00:00,763,10,101,76,48,180,32.9,0.171,63
764,0,2024-12-14 14:52:13.664794+00:00,764,2,122,70,27,0,36.8,0.340,27
765,0,2024-12-15 14:52:13.664794+00:00,765,5,121,72,23,112,26.2,0.245,30
766,1,2024-12-16 14:52:13.664794+00:00,766,1,126,60,0,0,30.1,0.349,47
767,0,2024-12-17 14:52:13.664794+00:00,767,1,93,70,31,0,30.4,0.315,23

In [45]:
# Importing dependencies
from feast import FeatureStore
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from joblib import dump

# Getting our FeatureStore
store = FeatureStore(repo_path=".")

# Retrieving the saved dataset and converting it to a DataFrame
training_df = store.get_saved_dataset(name="diabetes_dataset").to_df()

# Separating the features and labels
y = training_df['Outcome']
X = training_df.drop(
    labels=['Outcome', 'event_timestamp', "patient_id"], 
    axis=1)

# Splitting the dataset into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, 
                                                    y, 
                                                    stratify=y)

# Creating and training LogisticRegression
reg = LogisticRegression()
reg.fit(X=X_train[sorted(X_train)], y=y_train)

# Saving the model
dump(value=reg, filename="model.joblib")

/Users/bqkumar/Documents/Developements/feast_demo/venv/lib/python3.13/site-packages/feast/feature_store.py:1253: RuntimeWarning: Retrieving datasets is an experimental feature. This API is unstable and it could and most probably will be changed in the future. We do not guarantee that future changes will maintain backward compatibility.
  warnings.warn(
/Users/bqkumar/Documents/Developements/feast_demo/venv/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

['model.joblib']

In [46]:
# Importing dependencies
from feast import FeatureStore
from datetime import datetime, timedelta

# Getting our FeatureStore
store = FeatureStore(repo_path=".")

store.materialize_incremental(end_date = datetime.now())

Materializing 2 feature views to 2024-12-17 15:38:09+05:30 into the sqlite online store.

target_df_feature_view from 2024-12-05 15:38:09+05:30 to 2024-12-17 15:38:09+05:30:

  0%|                                                                        | 0/13 [00:00<?, ?it/s]WARNING:root:Cannot use sqlite_vec for vector search
100%|█████████████████████████████████████████████████████████████| 13/13 [00:00<00:00, 2198.27it/s]

predictors_df_feature_view from 2024-12-07 15:38:09+05:30 to 2024-12-17 21:08:09+05:30:

100%|█████████████████████████████████████████████████████████████| 11/11 [00:00<00:00, 3787.65it/s]

In [48]:
# Importing dependencies
from feast import FeatureStore
import pandas as pd
from joblib import load

# Getting our FeatureStore
store = FeatureStore(repo_path=".")

# Defining our features names
feast_features = [
    "predictors_df_feature_view:Pregnancies",
    "predictors_df_feature_view:Glucose",
    "predictors_df_feature_view:BloodPressure",
    "predictors_df_feature_view:SkinThickness",
    "predictors_df_feature_view:Insulin",
    "predictors_df_feature_view:BMI",
    "predictors_df_feature_view:DiabetesPedigreeFunction",
    "predictors_df_feature_view:Age",
]

# Getting the latest features
features = store.get_online_features(
    features=feast_features,
    entity_rows=[{"patient_id": 767}, {"patient_id": 766}]
).to_dict()

# Converting the features to a DataFrame
features_df = pd.DataFrame.from_dict(data=features)

WARNING:root:Cannot use sqlite_vec for vector search

In [49]:
features_df.head()

,patient_id,Insulin,BMI,BloodPressure,Age,DiabetesPedigreeFunction,Glucose,Pregnancies,SkinThickness
0,767,0,30.4,70,23,0.315,93,1,31
1,766,0,30.1,60,47,0.349,126,1,0

In [50]:
# Loading our model and doing inference
reg = load("model.joblib")
predictions = reg.predict(features_df[sorted(features_df.drop("patient_id", axis=1))])
print(predictions)

[0 0]